apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yml
- backend/service.yml
- frontend/deployment.yml
- frontend/service.yml
- ingress.yml
images:
- name: 654654554686.dkr.ecr.us-west-1.amazonaws.com/dvn-workshop/production/backend
  newName: 654654554686.dkr.ecr.us-west-1.amazonaws.com/dvn-workshop/production/backend
  newTag: ca11f0e1278312b5695e75d877190821c61d8cd6
- name: 654654554686.dkr.ecr.us-west-1.amazonaws.com/dvn-workshop/production/frontend
  newName: 654654554686.dkr.ecr.us-west-1.amazonaws.com/dvn-workshop/production/frontend
  newTag: 602e38fe13ce7b84110aa8261a738958c5e0935c
